### PR TITLE
Rainviewer, API key error, wrong forecasts, add UV index, fix wrong icon, add 60min rain forecast #15, #106, #132, #46, #135, #136

### PR DESCRIPTION
**Pull request by woheller69**
Final version of Rainviewer #15, fix for API key error #106, fix for wrong forecasts #132, user with own key can update current weather at any time, not only once per hour

### CODE REVIEW

**Comment by woheller69** [comment]
Here some preview of the current status. Except widgets, which I will not modify, and speed the app works great now in my view.
Screenshot_20201012-134150_Wetter
Screenshot_20201012-134208_Wetter
Screenshot_20201012-134219_Wetter
Screenshot_20201012-134239_Wetter
Screenshot_20201012-134252_Wetter

**Comment by sleep-yearning** [comment]
Thanks for all your work, revision is ongoing!

**Comment by woheller69** [comment]
Screenshot_20201015-105457
Screenshot_20201015-105443
Screenshot_20201015-105440

**Comment by woheller69** [comment]
BTW, I sent a link to my fork to the founder of RainViewer. He likes it :-)

**Comment by sleep-yearning** [comment]
Some questions about the code so far:
- This makes the old PR obsolete, correct? 
- How about the copyright of the added images? (Where do they come from?)
- Copyright of mapview/other code?
- why single calls for users with own api key? what is the benefit?

**Comment by woheller69** [comment]
Yes the other PR is obsolete. The other weather images were done by me. Are there more images?
The maps are done with Leaflet, attributions are shown at the bottom of the map. Map from Openstreetmap, attributions on map.
The html code for Rainviewer is from the founder of Rainviewer. (github luckyalvy). He is also happy with the attribution for RainViewer on the map and in the source code.
Advantage of single calls is, that by pressing the update button you get an update at any time. Updates for groups are provided once per hour only. But with one call API anyway all calls are single calls. Group calls for several cities are not available.
Single calls make the app faster as only the one city that is currently needed is updated.
Forecasts younger than 24h caused errors #132 and now with one call API they are not needed anymore as min/max etc for each day is provided by API.

**Comment by woheller69** [comment]
Rainviewer icon done by me. The world map is a screenshot from Openstreetmaps. That should be ok with the attributions shown.
The umbrella for 60min forecast and sun for sunrise/sunset are unicode characters

**Comment by woheller69** [comment]
Leaflet License:  "You're welcome, as the code is published under the very permissive 2-clause BSD License. Just make sure to attribute the use of the library somewhere in the app UI or the distribution (e.g. keep the Leaflet link on the map, or mention the use on the About page or a Readme file, etc.) and you'll be fine". (https://github.com/Leaflet/Leaflet/blob/master/FAQ.md)

RainViewer: 
Terms of Use:  API is free...
https://www.rainviewer.com/api.html
https://github.com/rainviewer/rainviewer-api-example from luckyalvy (founder of RainViewer)

**Comment by woheller69** [comment]
Added a chart with min/max temperature and precipitation instead of SunView.
Hope you like it.

Chart

**Comment by sleep-yearning** [comment]
The merging process is a bit complicated. I will push a merged version and then handle the commits that follow my last comment. 
Thanks for adressing my questions and thorough copyright explanations.
Since the images are done by you, I have to ask under which license you published them? 
I have another question regarding the database: Why did you create a new table Weekforecasts instead of extending the existing Forecasts table?

**Comment by woheller69** [comment]
My images are just rearrangements of the existing images. So I do not require special copyright for me.
Regarding Weekforecast: with the old API the app uses the 3 hour forecasts to  "calculate" the weather which is shown as week forecast. With one call API such calculations are no longer needed. One call API provides current, minutely, hourly, daily forecasts. Current is mapped into the existing current weather table, extended by the string with 60 min rain forecast.
The hourly forecasts are mapped to the existing 3h forecasts table, if the switch in preferences is set to 2day/hourly. If it is set to 5days/3h these course of day forecasts are fetched from the old forecast API as before. Daily forecasts for 8days are taken from one call API. These are stored in the new weekforecast table. For the widgets they should also be taken from there in future.

Regarding the chart: It was a bit tricky to align the temperature and rain charts. Transparency might be possible with setAlpha. I will give it a try.

If widgets are also fixed and startup gets a bit faster I think this will be the best open source weather app :-)

**Comment by woheller69** [comment]
Precipitation is transparent now. It was a bit more complicated than expected as  .setAlpha only applies to the line but not to the fill in a line chart. I changed precipitation into a bar chart and realigned it with the line chart again.

Barchart

**Comment by woheller69** [comment]
I noticed that the About screen is cut off on my phone. Embedding it into a scroll view did not work either. It scrolls a bit but not to the end... Ideas?

**Comment by woheller69** [comment]
Weekday is now also shown in the header of the course of day RecyclerView and is changed according to element on the left.

header

**Comment by sleep-yearning** [comment]
The changes have been incorporated, except 099e264 which resulted in some problems. The refresh button works well though, please make a new PR if you have a working solution.

Thanks a lot for all your contributions! Would you like to be mentioned by name under contributors?

Unfortunately it currently seems like we need to restrict the OneCallAPI based features on people using their own key. 
But the app has been improved a lot in general. Thanks again.

**Pull request closed without merging**
