### PR TITLE
Added rain/snow volume, wind speed and wind direction to course of day #59 #63 #122

### PR DESCRIPTION
**Pull request by woheller69**
Added columns precipitation, wind_speed, and wind_direction to database.
In precipitation 3h rain volume and 3h snow volume are added.
Course of day now shows precipitation in mm and wind in Bft + wind direction in addition. 
Added "rh" to "%" to make clear it is humidity not probability of rain or something else.
App needs fresh install (uninstall before) because of changed database.

wind

### CODE REVIEW

**Comment by sleep-yearning** [comment]
I cherry picked the changes to the ForecastActivity. 
The RainViewer is not merged yet

**Comment by Kamuno** [comment]
Good work on the rain map. Looks really good. I see you are still working on the feature. Can you post a message in here, when you think the feature is done and could be merged?

Thank you very much for your contribution!

**Comment by woheller69** [comment]
I think, I am done with it.
Todo: 
-Remove debug info about used APPID, once this problem is fixed in OwmApiData.getAPI_KEY();
-change to lat / lon instead of cityId, once this is available from citiestowatch

But for now it is done, and works great.
We should thank luckyalvy (Github user), who provided the API example, which I only modified a little.

**Comment by woheller69** [comment]
I took the latest version from your master and added rainviewer to it.
I pushed it to my newmaster branch. If you like, you can take rainviewer from there. Should be easier.

**Comment by woheller69** [comment]
In my newmaster branch I also have a solution for the wrong OWM APIKEY and removed the debug info for it from Rainviewer screen.

**Comment by sleep-yearning** [comment]
obsolete

**Pull request closed without merging**
